- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common
    - apache
    - mariadb
    - phpmyadmin
    - iptables

#- name: Reboot The Machine
#  command: 
