---
# tasks file for iptables
- name: Install iptables
  yum: name={{item}} state=present
  with_items: ['iptables', 'iptables-services']

- name: Reset iptables to blank state
  command: "{{item}}"
  with_items:
    - 'iptables -P FORWARD ACCEPT'
    - 'iptables -P INPUT ACCEPT'
    - 'iptables -F'
    - 'iptables -X
'
- name: Configuring packet filtering using IPtables
  template: src=iptables.j2 dest=/etc/sysconfig/iptables owner=root group=root mode=0644


#- name: Adding Rules
#  iptables: chain=INPUT in_interface=eth0 protocol=tcp destination_port={{item}} ctstate=NEW,ESTABLISHED jump=ACCEPT comment="Allow External Request for Web on 80"
#  with_items:
#    - 80
#    - 443
#  iptables: chain=INPUT ctstate=ESTABLISHED,RELATED jump=ACCEPT
- name: Enable iptables service
  service: name=iptables enabled=yes state=restarted

- name: Saving Roles
  command: /usr/libexec/iptables/iptables.init save

#- name: Enable iptables service
#  service: name=iptables enabled=yes state=restarted
